### ISSUE TITLE
Guzzle warnings

### ISSUE THREAD

**Issue by candacelebel** [unm-art/WMS-Labeling#10]
During php composer.phar install on Ubuntu 16 running PHP 7 I got:

package guzzle/common is abandoned, you should avoid using it.  Use guzzle/guzzle instead.
package guzzle/stream is abandoned, you should avoid using it.  Use guzzle/guzzle instead.
package guzzle/parser is abandoned, you should avoid using it.  Use guzzle/guzzle instead.
package guzzle/http is abandoned, you should avoid using it.  Use guzzle/guzzle instead.

**Comment by librarywebchic** [comment]
This was fixed when some unnecessary dev-dependencies were removed
