### ISSUE TITLE
Curl Error

### ISSUE THREAD

**Issue by rkuehn-uofl** [unm-art/WMS-Labeling#11]
I receive the following response when generating a label:

Please check your config.php file. Your URL may be invalid. 
Curl Error - 27 - SSL: couldn't create a context: error:140A90C4:SSL routines:SSL_CTX_new:null ssl method passed

Running: Ubuntu 16.04.3, NGINX 1.10.3, PHP 7.0.22

**Comment by librarywebchic** [comment]
I believe this was fixed as of commit 9f660108142898170edd3653c4b3ff0a62ff1202
