### ISSUE TITLE
Authorization broken?

### ISSUE THREAD

**Issue by larrydeck** [unm-art/WMS-Labeling#17]
The code in this repository no longer seems to work, perhaps because of recent fixes to the way it authenticates. When I run it and try a barcode in the web form, I get this error :

127.0.0.1:38020 [500]: /inc/fetch_labels.php - Uncaught InvalidArgumentException: Required option not passed: "access_token" in /home/ldeck/newlabeltest/WMS-Labeling/vendor/league/oauth2-client/src/Token/AccessToken.php:62
Stack trace:
#0 /home/ldeck/newlabeltest/WMS-Labeling/vendor/league/oauth2-client/src/Provider/AbstractProvider.php(746): League\OAuth2\Client\Token\AccessToken->__construct(Array)
#1 /home/ldeck/newlabeltest/WMS-Labeling/vendor/league/oauth2-client/src/Provider/AbstractProvider.php(544): League\OAuth2\Client\Provider\AbstractProvider->createAccessToken(Array, Object(League\OAuth2\Client\Grant\ClientCredentials))
#2 /home/ldeck/newlabeltest/WMS-Labeling/inc/fetch_labels.php(89): League\OAuth2\Client\Provider\AbstractProvider->getAccessToken(Object(League\OAuth2\Client\Grant\ClientCredentials), Array)
#3 {main}
  thrown in /home/ldeck/newlabeltest/WMS-Labeling/vendor/league/oauth2-client/src/Token/AccessToken.php on line 62

**Comment by jonahlyn** [comment]
Hi Larry.

Unfortunately I am not able to replicate this problem. Can you please verify that you have valid settings (WSKEY, secret, etc.) in the config.php file?

Thanks
Jonahlyn

**Comment by larrydeck** [comment]
Thanks for responding. I do have WSKEY and secret set in config.php. 

I notice that config no longer has pricipalID/principalIDNS. which I thought were necessary for using those APIs. Is that deliberate?

**Comment by larrydeck** [comment]
Did not intend to close, sorry.

**Comment by jonahlyn** [comment]
Yes the removal of the principleID/principalIDNS was [deliberate.](https://github.com/unm-art/WMS-Labeling/commit/0bffe087b0ca64b0e3e1014b77e70c90afc860c4#diff-77258f9bb856f0f215963527f08dde42)

Can you compare the contents of the config.php.template with your config.php and make sure you have all the required settings in there? 

You may also want to log in to [OCLC's developer site](https://platform.worldcat.org/wskey) and check that the WSKEY isn't expired.

**Comment by larrydeck** [comment]
The WSKEY is okay -- API explorer and Postman both work fine with the key, as does an earlier version of your app that we have had running since September. Apart from the principalID/principalIDNS absent from the new one, there doesn't seem to be any difference.

The API explorer for WMS Collection Management API still asks for principalID/principalIDNS if you use "my credentials". Maybe this has yet to be updated? Maybe older keys require it but not newer ones? I'm at a loss.

**Comment by jonahlyn** [comment]
Unfortunately, I am also at a loss. I changed our config.php on a test system to an invalid WSKEY and did receive the same error message you are seeing. It sounds like you have a valid key though. I'm not sure. You may have to open a ticket with OCLC if you haven't already. Good luck.

**Comment by larrydeck** [comment]
Thanks for your attention, I'm having the same problem with OCLC's new "gists", so I'll open a ticket with them and see if they can figure it out.

**Comment by nicalico** [comment]
We got the very same problem. I opened a ticket with OCLC and got that answer : 

> "Your WSkey did not have a default user associated with it. I've added this so it should work with the Label application now" 

It solved our problem.

**Comment by larrydeck** [comment]
Okay, thanks.

**Comment by wallacelibrary** [comment]
Thank you. I am having this same issue. Will follow @nicalico 's steps above.
