### ISSUE TITLE
Change of ownership

### ISSUE THREAD

**Issue by jonahlyn** [unm-art/WMS-Labeling#7]
Cameron,

Hope things are going well for you.

If you still get these, can you please turn over ownership of the unm-art organization and the WMS-Labeling repo to me, please?

Thanks!
Jonahlyn

**Comment by CameronRStewart** [comment]
Hey Jonahlyn, 

Things are going quite well.  I certainly hope it's the same for you and that things are settling into place back there.  If you _insist_ Ill go ahead and make you the owner of these.

I believe that I have now made you an owner for both.  For some reason, I cant add myself as an outside collaborator.  Looks like you'll have to do that.  Good luck!

Cameron
